CREATE TABLE "distribution_programs" ("id" text PRIMARY KEY NOT NULL, "org_id" text NOT NULL, "project_id" text, "name" text NOT NULL, "objective" text NOT NULL, "primary_conversion" text NOT NULL, "secondary_conversion" text, "target_value" integer NOT NULL, "target_date" timestamp with time zone, "budget_cents" integer, "status" text DEFAULT 'ACTIVE' NOT NULL, "scoring_weights" jsonb NOT NULL, "autonomy_settings" jsonb NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL);
--> statement-breakpoint
CREATE UNIQUE INDEX "distribution_programs_org_name_idx" ON "distribution_programs" USING btree ("org_id","name");
--> statement-breakpoint
CREATE TABLE "distribution_hypotheses" ("id" text PRIMARY KEY NOT NULL, "org_id" text NOT NULL, "program_id" text NOT NULL REFERENCES "distribution_programs"("id"), "code" text NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "status" text DEFAULT 'ACTIVE' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL);
--> statement-breakpoint
CREATE UNIQUE INDEX "distribution_hypotheses_program_code_idx" ON "distribution_hypotheses" USING btree ("program_id","code"); CREATE INDEX "distribution_hypotheses_org_idx" ON "distribution_hypotheses" USING btree ("org_id");
--> statement-breakpoint
CREATE TABLE "distribution_signals" ("id" text PRIMARY KEY NOT NULL, "org_id" text NOT NULL, "provider" text NOT NULL, "provider_external_id" text, "platform" text NOT NULL, "url" text, "author_handle" text, "author_name" text, "content" text NOT NULL, "published_at" timestamp with time zone, "captured_at" timestamp with time zone DEFAULT now() NOT NULL, "raw_payload" jsonb NOT NULL, "dedupe_key" text NOT NULL, "processing_status" text DEFAULT 'NEW' NOT NULL);
--> statement-breakpoint
CREATE UNIQUE INDEX "distribution_signals_org_dedupe_idx" ON "distribution_signals" USING btree ("org_id","dedupe_key"); CREATE INDEX "distribution_signals_processing_idx" ON "distribution_signals" USING btree ("org_id","processing_status");
--> statement-breakpoint
CREATE TABLE "distribution_opportunities" ("id" text PRIMARY KEY NOT NULL, "org_id" text NOT NULL, "signal_id" text REFERENCES "distribution_signals"("id"), "program_id" text NOT NULL REFERENCES "distribution_programs"("id"), "opportunity_type" text NOT NULL, "hypothesis_id" text REFERENCES "distribution_hypotheses"("id"), "audience_type" text NOT NULL, "problem_summary" text NOT NULL, "intent_type" text NOT NULL, "fit_score" integer NOT NULL, "intent_score" integer NOT NULL, "freshness_score" integer NOT NULL, "audience_score" integer NOT NULL, "engagement_score" integer NOT NULL, "overall_score" integer NOT NULL, "reasoning" text NOT NULL, "recommended_action_type" text NOT NULL, "state" text DEFAULT 'NEW' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL);
--> statement-breakpoint
CREATE UNIQUE INDEX "distribution_opportunities_signal_program_idx" ON "distribution_opportunities" USING btree ("signal_id","program_id"); CREATE INDEX "distribution_opportunities_queue_idx" ON "distribution_opportunities" USING btree ("org_id","program_id","state");
--> statement-breakpoint
CREATE TABLE "distribution_drafts" ("id" text PRIMARY KEY NOT NULL, "org_id" text NOT NULL, "opportunity_id" text NOT NULL REFERENCES "distribution_opportunities"("id"), "body" text NOT NULL, "model_metadata" jsonb, "version" integer NOT NULL, "status" text NOT NULL, "edited_by_human" boolean DEFAULT false NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL); CREATE UNIQUE INDEX "distribution_drafts_opportunity_version_idx" ON "distribution_drafts" USING btree ("opportunity_id","version"); CREATE INDEX "distribution_drafts_org_idx" ON "distribution_drafts" USING btree ("org_id");
--> statement-breakpoint
CREATE TABLE "distribution_actions" ("id" text PRIMARY KEY NOT NULL, "org_id" text NOT NULL, "opportunity_id" text NOT NULL REFERENCES "distribution_opportunities"("id"), "action_type" text NOT NULL, "final_content" text, "external_url" text, "acted_at" timestamp with time zone, "actor" text NOT NULL, "status" text NOT NULL, "metadata" jsonb, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL); CREATE INDEX "distribution_actions_opportunity_idx" ON "distribution_actions" USING btree ("org_id","opportunity_id");
--> statement-breakpoint
CREATE TABLE "distribution_outcomes" ("id" text PRIMARY KEY NOT NULL, "org_id" text NOT NULL, "opportunity_id" text REFERENCES "distribution_opportunities"("id"), "action_id" text REFERENCES "distribution_actions"("id"), "outcome_type" text NOT NULL, "value" numeric, "source" text NOT NULL, "confidence" integer, "occurred_at" timestamp with time zone NOT NULL, "metadata" jsonb, "created_at" timestamp with time zone DEFAULT now() NOT NULL); CREATE INDEX "distribution_outcomes_opportunity_idx" ON "distribution_outcomes" USING btree ("org_id","opportunity_id");
