import { Link } from 'react-router-dom';
import { SelvedgeLockup } from '../components/Logo.js';
import { AgentChip } from '../components/AgentChip.js';
import { btnGhost, btnPrimary, eyebrowCls } from '../components/ui.js';

function Message({ who, agent, children, muted = false }: { who: string; agent?: string; children: React.ReactNode; muted?: boolean }) {
  return <div className={`landing-message ${muted ? 'landing-message-muted' : ''}`}><div className="flex items-center gap-2">{agent && <AgentChip agent={agent} />}<p className={eyebrowCls}>{who}</p></div><div className="mt-2 text-body-lg text-ink">{children}</div></div>;
}
function ContextLine({ children }: { children: React.ReactNode }) { return <p className="landing-context-line font-mono text-tech text-ink-quiet">{children}</p>; }
function ProjectHeader({ detail }: { detail: string }) {
  return <div className="flex items-center justify-between gap-4 border-b border-hairline px-4 py-3 sm:px-6"><div><p className="text-body font-medium text-ink">Loom / Onboarding</p><p className="mt-0.5 text-meta text-ink-quiet">One project conversation</p></div><p className="font-mono text-tech text-ink-quiet">{detail}</p></div>;
}

/** Used by the landing page and the social-card capture script. */
export function SampleThread({ short = false, caption = true }: { short?: boolean; caption?: boolean } = {}) {
  return <div><div className="landing-thread overflow-hidden border border-hairline bg-panel"><ProjectHeader detail="12 conversations in context" /><div className="px-4 py-5 sm:px-6 sm:py-7">
    <Message who="You">We need to rethink onboarding. <span className="text-brass">@claude</span>, make the strongest case for removing the setup wizard. <span className="text-brass">@gpt</span>, disagree with it.</Message>
    <div className="landing-answer-pair mt-6"><Message who="Claude" agent="claude">Remove it. The wizard asks people to describe a project before they have seen Selvedge use one. Let them bring a conversation first; the project can take shape from evidence.</Message><Message who="GPT" agent="gpt">I disagree with Claude. A short wizard can establish the project boundary before imported chats muddy it. Cut it to one decision: what belongs here?</Message></div>
    {!short && <><ContextLine>↳ both answers used the same 12 imported conversations</ContextLine><Message who="You" muted>Keep the boundary question. Move it after import. <span className="text-brass">@codex</span> make that change in the onboarding branch.</Message></>}
  </div>{!short && <div className="border-t border-hairline px-4 py-3 sm:px-6"><div className="flex items-center gap-2 font-mono text-tech text-ink-dim"><AgentChip agent="codex" /><span className="text-healthy">✓</span> updated onboarding · 4 files · preview ready</div></div>}</div>{caption && <p className="mt-2 text-meta text-ink-quiet">A sample project conversation.</p>}</div>;
}

function SectionIntro({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return <div className="landing-section-intro"><p className="font-mono text-tech text-action-bright">{number}</p><h2 className="mt-3 font-display text-section font-medium text-ink">{title}</h2><p className="mt-4 max-w-md text-body-lg text-ink-dim">{children}</p></div>;
}

export function Landing() {
  return <div className="overflow-hidden">
    <header className="landing-nav sticky top-0 z-20 border-b border-hairline"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6"><SelvedgeLockup tone="chalk" className="h-7 w-auto" /><div className="flex items-center gap-1 sm:gap-2"><Link to="/sign-in" className={btnGhost}>Sign in</Link><Link to="/sign-up" className={btnPrimary}>Start free</Link></div></div></header>
    <main>
      <section className="landing-hero mx-auto max-w-6xl px-4 pt-14 sm:px-6 sm:pt-20 lg:pt-24"><div className="relative z-10 max-w-4xl"><p className={eyebrowCls}>All your AI. One conversation.</p><h1 className="mt-4 max-w-4xl font-display text-hero font-medium text-ink">Your AI should know what the others already know.</h1><div className="mt-6 flex max-w-3xl flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-xl text-hero-sub text-ink-dim">Claude, GPT, Codex and the rest of your AI stack, working from one project history.</p><Link to="/sign-up" className={`${btnPrimary} shrink-0 self-start sm:self-auto`}>Start a project</Link></div></div><div className="landing-hero-thread mt-12 lg:mt-16"><SampleThread caption={false} /></div><p className="landing-scroll-cue font-mono text-tech text-ink-quiet">Continue through the project ↓</p></section>

      <section aria-label="One project, many minds" className="landing-section landing-many mx-auto max-w-6xl px-4 sm:px-6"><SectionIntro number="01" title="One project. Many minds.">Call in one model or several. Each reads the same history and answers in its own name.</SectionIntro><div className="landing-transcript"><ContextLine>loom / pricing · context carried forward from onboarding</ContextLine><Message who="You">Which pricing change creates the least confusion? <span className="text-brass">@gemini @claude @gpt</span></Message><Message who="Gemini" agent="gemini">Keep the current tiers. Change the usage language, not the structure.</Message><Message who="Claude" agent="claude">Collapse to two tiers. The middle option is doing no useful work.</Message><Message who="GPT" agent="gpt">Keep three tiers, but price the middle one as the obvious default.</Message></div></section>

      <section aria-label="Bring old conversations" className="landing-section landing-import mx-auto max-w-6xl px-4 sm:px-6"><div className="landing-import-stack" aria-label="Imported conversations becoming project context"><div className="landing-import-source"><span>ChatGPT</span><strong>Early customer interviews</strong><small>18 messages · Feb 12</small></div><div className="landing-import-source"><span>Claude</span><strong>Onboarding teardown</strong><small>31 messages · Mar 04</small></div><div className="landing-import-source"><span>Gemini</span><strong>Competitor notes</strong><small>9 messages · Mar 19</small></div><div className="landing-import-result font-mono text-tech"><span className="text-healthy">✓</span> 3 conversations added to Loom</div></div><SectionIntro number="02" title="Stop starting over.">Bring in the conversations that got you here. The next AI starts with the decisions, questions, and dead ends already in the project.</SectionIntro></section>

      <section aria-label="Compare models" className="landing-section landing-compare mx-auto max-w-6xl px-4 sm:px-6"><SectionIntro number="03" title="Ask twice.">Give the same question to two models. Keep the disagreement visible. Decide for yourself.</SectionIntro><div className="landing-compare-stage"><p className="border-b border-hairline pb-5 text-body-lg text-ink">Should the free plan include conversation imports?</p><div className="landing-comparison"><div><AgentChip agent="claude" /><p>Yes. Import is the moment Selvedge proves its value. Limiting it delays understanding.</p><span>Include 3 imports</span></div><div><AgentChip agent="gpt" /><p>No. Imports have durable storage cost and make the free tier easy to treat as an archive.</p><span>Preview before upgrading</span></div></div></div></section>

      <section aria-label="Coding agents in the project" className="landing-section landing-building mx-auto max-w-6xl px-4 sm:px-6"><div className="landing-code-run font-mono text-tech"><div className="border-b border-hairline px-5 py-4 text-ink-quiet">loom / onboarding · Codex</div><div className="space-y-3 px-5 py-6 text-ink-dim"><p><span className="text-action-bright">→</span> Read the pricing decision above</p><p><span className="text-action-bright">→</span> Updated import limit copy</p><p><span className="text-action-bright">→</span> Changed upgrade boundary</p><p><span className="text-healthy">✓</span> 14 tests passed</p><p><span className="text-healthy">✓</span> preview ready · 7c3a1d8</p></div></div><SectionIntro number="04" title="Building belongs in the conversation.">Thinking and implementation share one history. Codex, Claude Code, and Cursor enter the same project instead of beginning in a blank terminal.</SectionIntro></section>

      <section aria-label="Project history" className="landing-section landing-memory mx-auto max-w-6xl px-4 sm:px-6"><SectionIntro number="05" title="The project remembers.">Close the tab. Change models. Come back in six months. The project still knows how the work arrived here.</SectionIntro><div className="landing-history font-mono text-tech"><div><time>FEB 12</time><span>18 ChatGPT messages imported</span></div><div><time>MAR 04</time><span>Onboarding wizard challenged by Claude</span></div><div><time>MAR 05</time><span>Boundary question kept after GPT disagreed</span></div><div><time>MAR 06</time><span>Codex shipped 7c3a1d8</span></div><div><time>AUG 22</time><span>You asked “why is it like this?”</span></div></div></section>

      <section className="mx-auto max-w-6xl px-4 pb-24 pt-10 sm:px-6 sm:pb-32"><p className={eyebrowCls}>One project conversation</p><h2 className="mt-4 max-w-4xl font-display text-hero font-medium text-ink">Your work doesn’t belong to one AI anymore.</h2><div className="mt-8 flex flex-wrap items-center gap-5"><Link to="/sign-up" className={btnPrimary}>Start free</Link><p className="font-mono text-tech text-ink-quiet">Bring a conversation, a repo, or just a question.</p></div></section>
    </main>
    <footer className="border-t border-hairline"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-8 text-meta text-ink-quiet sm:px-6"><p><span className="font-display italic text-ink-dim">selvedge</span> — the project layer across the AI you already use.</p><div className="flex gap-5"><Link to="/docs">Docs</Link><Link to="/security">Security</Link><Link to="/sign-in">Sign in</Link></div></div></footer>
  </div>;
}
