import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ImportReplit } from '../components/ImportReplit.js';
import { Pane } from '../components/ui.js';
import type { MigrationSource } from '../../shared/types/migration.js';

const sources: Array<{ id: MigrationSource; name: string; group: 'hosted' | 'repo'; state: 'ready' | 'connect' | 'planned'; note: string; guide?: string[] }> = [
  { id: 'replit', name: 'Replit', group: 'hosted', state: 'ready', note: 'Bring the app export. Selvedge inspects it, creates the repo and project map, and opens the workspace.' },
  { id: 'lovable', name: 'Lovable', group: 'hosted', state: 'planned', note: 'The direct source adapter is next. We will not claim access Selvedge does not have yet.' },
  { id: 'bolt', name: 'Bolt', group: 'hosted', state: 'planned', note: 'The direct source adapter is next. Your current production environment remains untouched.' },
  { id: 'base44', name: 'Base44', group: 'hosted', state: 'planned', note: 'The direct source adapter is next. Your current production environment remains untouched.' },
  { id: 'github', name: 'GitHub', group: 'repo', state: 'connect', note: 'Connect an existing repository. Selvedge already understands repos as owner-controlled project sources.', guide: ['Choose the repository.', 'Confirm the project boundary.', 'Let Selvedge map it and open the workspace.'] },
  { id: 'codex', name: 'Codex', group: 'repo', state: 'connect', note: 'Codex can keep doing coding work. Selvedge becomes the durable home for the repository, decisions, previews, verification, and releases.', guide: ['Commit or push the project to GitHub.', 'Connect that repository to Selvedge.', 'Continue in one project conversation; use Codex or another worker whenever it fits.'] },
  { id: 'claude-code', name: 'Claude Code', group: 'repo', state: 'connect', note: 'Claude Code remains a capable worker. Selvedge keeps the project context and operating record from becoming tied to one Claude session or machine.', guide: ['Push the working repository to GitHub.', 'Connect it to Selvedge.', 'Add the decisions or conversations worth preserving, then continue with any agent.'] },
  { id: 'cursor', name: 'Cursor', group: 'repo', state: 'connect', note: 'Cursor is where you may edit; Selvedge is where the project lives. The repository, context, preview, evidence, and shipping workflow stay together.', guide: ['Commit your current Cursor workspace.', 'Push it to GitHub and connect the repository.', 'Use Selvedge to manage future agent work, verification, and releases.'] },
];

export function Migrate() {
  const [source, setSource] = useState<MigrationSource>('replit');
  const chosen = sources.find((item) => item.id === source)!;
  return <div className="animate-settle mx-auto max-w-5xl px-5 pb-24 pt-12 sm:px-8 sm:pt-16">
    <header className="max-w-3xl"><p className="section-label">Bring your project home</p><h1 className="mt-4 font-display text-[clamp(2.7rem,6vw,4.6rem)] leading-none tracking-[-.045em] text-ink">Where is your app today?</h1><p className="mt-5 text-lede text-ink-dim">Choose the source once. Selvedge builds the inventory, preserves the original, and takes you to a working copy.</p></header>
    <div className="mt-10 space-y-6">{(['hosted', 'repo'] as const).map((group) => <section key={group}><p className="mb-3 section-label">{group === 'hosted' ? 'Leaving a hosted builder' : 'Bringing work from a coding agent or editor'}</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{sources.filter((item) => item.group === group).map((item) => <button type="button" key={item.id} onClick={() => setSource(item.id)} aria-pressed={source === item.id} className={`rounded-card border p-4 text-left ${source === item.id ? 'border-action bg-sage' : 'border-hairline bg-panel hover:border-action/50'}`}><strong className="block text-body text-ink">{item.name}</strong><span className="mt-2 block font-mono text-tech text-ink-quiet">{item.state === 'ready' ? 'AVAILABLE' : item.state === 'connect' ? 'REPOSITORY HANDOFF' : 'ADAPTER PLANNED'}</span></button>)}</div></section>)}</div>
    <Pane className="mt-6 p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="section-label">Leaving {chosen.name}</p><h2 className="mt-2 font-display text-3xl text-ink">Selvedge does the inventory.</h2><p className="mt-2 max-w-2xl text-body text-ink-dim">{chosen.note}</p></div><span className="rounded-full bg-panel-soft px-3 py-1.5 font-mono text-tech text-ink-dim">Original stays live</span></div>
      {source === 'replit' && <div className="mt-6"><ImportReplit /></div>}
      {chosen.state === 'connect' && <div className="mt-6 rounded-inset border border-hairline bg-panel-soft p-4"><ol className="grid gap-2 text-body text-ink-dim">{chosen.guide?.map((step, index) => <li key={step}><span className="mr-2 font-mono text-tech text-action-bright">0{index + 1}</span>{step}</li>)}</ol><Link to="/projects" className="mt-4 inline-block rounded-full bg-action px-5 py-2.5 text-body font-medium text-white">Connect or choose the repository →</Link></div>}
      {chosen.state === 'planned' && <div className="mt-6 rounded-inset border border-hairline bg-panel-soft p-4"><p className="text-body text-ink">This adapter is not connected yet.</p><p className="mt-1 text-meta text-ink-dim">For now, export the project into GitHub and bring that repository into Selvedge. We are keeping this boundary explicit instead of presenting a manual checklist as an autonomous migration.</p><Link to="/projects" className="mt-3 inline-block text-body text-action-bright hover:underline">Bring the GitHub repository →</Link></div>}
    </Pane>
    <ol className="mt-8 grid gap-3 md:grid-cols-3"><li className="rounded-card bg-panel p-5"><span className="font-mono text-tech text-action-bright">01</span><strong className="mt-3 block text-body text-ink">Selvedge inspects</strong><p className="mt-1 text-meta text-ink-dim">Code, runtime, data, auth, storage, jobs, integrations, secrets, domains and hosting.</p></li><li className="rounded-card bg-panel p-5"><span className="font-mono text-tech text-action-bright">02</span><strong className="mt-3 block text-body text-ink">Agents build the copy</strong><p className="mt-1 text-meta text-ink-dim">The workspace is isolated. The current production app is not modified.</p></li><li className="rounded-card bg-panel p-5"><span className="font-mono text-tech text-action-bright">03</span><strong className="mt-3 block text-body text-ink">You review the result</strong><p className="mt-1 text-meta text-ink-dim">Preview and observed evidence come before any production cutover.</p></li></ol>
  </div>;
}
