import { useEffect, useState, type ReactNode } from 'react';
import { NavLink, Navigate, Route, Routes } from 'react-router-dom';
import { api } from '../lib/api.js';

const tabClass = ({ isActive }: { isActive: boolean }) => `rounded-inset px-3 py-1.5 text-body font-medium ${isActive ? 'bg-panel-soft text-ink' : 'text-ink-quiet hover:text-ink-dim'}`;

type Program = {
  name: string; objective: string; primaryConversion: string; secondaryConversion: string | null; targetValue: number;
  targetDate: string | null; budgetCents: number | null; status: string;
  scoringWeights: Record<string, number>; autonomySettings: Record<string, string>;
  hypotheses: Array<{ id: string; code: string; name: string; description: string; status: string }>;
  currentValue:number; timeRemainingDays:number|null; recommendation:string; experiments:Array<{id:string;name:string;status:string;successMetric:string}>;
  policy: DistributionPolicy; planner: Planner;
};
type DistributionPolicy={goal:string;primary_metric:string;target:number;deadline:string|null;budget_cents:number;allowed_channels:Record<string,boolean>;allowed_action_types:string[];autonomy:Record<string,string>;daily_action_cap:number;per_platform_action_cap:number;minimum_opportunity_score:number;maximum_risk:number;hypothesis_allocation:Record<string,number>};
type Recommendation={opportunityId:string;platform:string;hypothesis:string;allocationType:'EXPLORATION'|'EXPLOITATION';whyOpportunity:string;whyHypothesis:string;whyChannel:string;evidence:string};
type Planner={recommendations:Recommendation[];reviewedSignals:number;attentionCount:number};
type BuskaStatus = { configured: boolean; lastSuccessfulScan: string | null; nextScheduledScan: string; signalsIngested: number; lastError: string | null; lastScan: { status: string; recordsFound: number; recordsInserted: number; duplicates: number; failures: number } | null };

function AccessGate({ children }: { children: ReactNode }) {
  const [state, setState] = useState<'checking' | 'allowed' | 'denied'>('checking');
  useEffect(() => { api.get('/api/ops/distribution/access').then(() => setState('allowed')).catch(() => setState('denied')); }, []);
  if (state === 'checking') return null;
  if (state === 'denied') return <section className="rounded-card border border-hairline bg-panel p-6"><p className="text-label uppercase tracking-widest text-ink-quiet">Not found</p><h1 className="mt-2 font-display text-2xl text-ink">There’s nothing here for this account.</h1></section>;
  return children;
}

type Draft = { id: string; body: string; responseMode: string; status: string };
type Opportunity = { id:string; state:string; overallScore:number; platform:string|null; author:string|null; content:string|null; url:string|null; publishedAt:string|null; hypothesis:string; audienceType:string; problemSummary:string; reasoning:string; recommendedActionType:string; draft:Draft|null };

function ReviewCard({ item, reload }: { item: Opportunity; reload: () => Promise<void> }) {
  const [body, setBody] = useState(item.draft?.body ?? '');
  const [message, setMessage] = useState<string | null>(null);
  const act = async (work: () => Promise<unknown>, success: string) => { try { await work(); setMessage(success); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'That did not go through.'); } };
  return <article className="rounded-card border border-hairline bg-panel p-4">
    <div className="flex justify-between"><span className="font-mono text-action-bright">{item.overallScore} · {item.hypothesis} · {item.platform}</span><span className="text-meta text-ink-quiet">{item.publishedAt ? new Date(item.publishedAt).toLocaleString() : 'Unknown age'}</span></div>
    <p className="mt-2 text-meta text-ink-quiet">{item.author ?? 'Unknown author'} · {humanize(item.audienceType)}</p>
    <blockquote className="mt-3 border-l-2 border-hairline pl-3 text-body text-ink-dim">{item.content?.slice(0,320)}</blockquote>
    <h2 className="mt-3 font-medium text-ink">{item.problemSummary}</h2><p className="mt-1 text-body text-ink-dim">{item.reasoning}</p>
    {item.draft && <div className="mt-4"><p className="text-label uppercase tracking-widest text-ink-quiet">{humanize(item.draft.responseMode)}</p><textarea aria-label="Draft response" value={body} onChange={(e)=>setBody(e.target.value)} rows={5} className="mt-2 w-full rounded-inset border border-hairline bg-panel-soft p-3 text-body text-ink"/></div>}
    <div className="mt-4 flex flex-wrap gap-2">
      {!item.draft && <button onClick={()=>void act(()=>api.post(`/api/ops/distribution/opportunities/${item.id}/draft`,{}),'Draft ready.')} className="rounded-inset bg-action px-3 py-1.5 text-body">Draft response</button>}
      {item.draft?.status === 'DRAFTED' && <><button onClick={()=>void act(()=>api.patch(`/api/ops/distribution/drafts/${item.draft!.id}`,{body}),'Edit saved.')} className="rounded-inset border border-hairline px-3 py-1.5 text-body">Save edit</button><button onClick={()=>void act(()=>api.post(`/api/ops/distribution/drafts/${item.draft!.id}/approve`,{}),'Approved to post.')} className="rounded-inset bg-action px-3 py-1.5 text-body">Approve</button></>}
      {item.draft && <button onClick={()=>void navigator.clipboard.writeText(body).then(()=>setMessage('Copied.'))} className="rounded-inset border border-hairline px-3 py-1.5 text-body">Copy</button>}
      {item.state === 'APPROVED' && <button onClick={()=>{const url=window.prompt('Public response URL (optional)')?.trim();void act(()=>api.post(`/api/ops/distribution/opportunities/${item.id}/posted`,url?{url}:{}),'Marked posted.');}} className="rounded-inset bg-action px-3 py-1.5 text-body">Mark posted</button>}
      {item.state === 'ACTED' && <button onClick={()=>{const type=window.prompt('Outcome: SIGNUP, PROJECT_CONNECTED, PAID, REPLY_RECEIVED, SITE_VISIT, or SELF_REPORTED')?.trim().toUpperCase();if(!type)return;const confidence=window.prompt('Confidence: confirmed, likely, or possible','confirmed')?.trim().toLowerCase();if(!confidence)return;const reason=window.prompt('Reason (optional)')?.trim();void act(()=>api.post(`/api/ops/distribution/opportunities/${item.id}/outcomes`,{type,confidence,reason}),'Outcome attributed.');}} className="rounded-inset border border-hairline px-3 py-1.5 text-body">Attribute outcome</button>}
      <button onClick={()=>void act(()=>api.post(`/api/ops/distribution/opportunities/${item.id}/skip`,{}),'Skipped.')} className="rounded-inset border border-hairline px-3 py-1.5 text-body">Skip</button>
      {item.url && <a href={item.url} target="_blank" rel="noreferrer" className="rounded-inset border border-hairline px-3 py-1.5 text-body">Open original</a>}
    </div>{message && <p className="mt-2 text-meta text-ink-dim">{message}</p>}
  </article>;
}

function Today() {
  type TodayData={opportunities:Opportunity[];currentValue:number;targetValue:number;reviewedSignals:number;attentionCount:number;planner:Planner};
  const [data,setData]=useState<TodayData|null>(null); const [platform,setPlatform]=useState('ALL'); const [hypothesis,setHypothesis]=useState('ALL'); const [minimum,setMinimum]=useState(75);
  const [manual,setManual]=useState({platform:'reddit',url:'',content:''}); const [manualMessage,setManualMessage]=useState<string|null>(null);
  const load=()=>api.get<TodayData>('/api/ops/distribution/today').then(setData); useEffect(()=>{void load();},[]); if(!data)return null; const items=data.opportunities;
  const shown=items.filter(x=>(platform==='ALL'||x.platform===platform)&&(hypothesis==='ALL'||x.hypothesis===hypothesis)&&x.overallScore>=minimum);
  const addManual=async()=>{setManualMessage('Classifying with the same blind rubric…');try{await api.post('/api/ops/distribution/opportunities/manual',manual);setManual({platform:manual.platform,url:'',content:''});setManualMessage('Human-found opportunity added.');await load();}catch(e){setManualMessage(e instanceof Error?e.message:'Could not add opportunity.');}};
  return <section><div className="flex items-end justify-between"><div><p className="text-label font-semibold uppercase tracking-widest text-ink-quiet">Goal: {data.targetValue} connected projects · {data.currentValue}/{data.targetValue}</p><h1 className="mt-2 font-display text-3xl text-ink">Selvedge reviewed {data.reviewedSignals} signals. {data.attentionCount?`${data.attentionCount} deserve attention.`:'Nothing strong enough right now.'}</h1></div><button onClick={()=>void api.post<{approved:number}>('/api/ops/distribution/drafts/approve-high-confidence',{}).then(load)} className="rounded-inset border border-hairline px-3 py-2 text-body">Approve all high-confidence</button></div>
  {data.planner.recommendations.length>0&&<section className="mt-5 rounded-card border border-hairline bg-panel p-4"><h2 className="font-display text-xl text-ink">Today’s allocation</h2><div className="mt-3 space-y-3">{data.planner.recommendations.map(r=><div key={r.opportunityId} className="rounded-inset bg-panel-soft p-3 text-body"><strong className="text-ink">{humanize(r.allocationType)} · {r.hypothesis} on {r.platform}</strong><p className="mt-1 text-ink-dim">{r.whyOpportunity} {r.whyHypothesis} {r.whyChannel}</p><p className="mt-1 text-meta text-ink-quiet">Evidence: {r.evidence}</p></div>)}</div></section>}
  <form className="mt-5 rounded-card border border-hairline bg-panel p-4" onSubmit={e=>{e.preventDefault();void addManual();}}><h2 className="font-display text-xl text-ink">Add an opportunity you found</h2><p className="mt-1 text-meta text-ink-quiet">It is scored by the same classifier without being told who found it.</p><div className="mt-3 grid gap-2 sm:grid-cols-[10rem_1fr]"><input aria-label="Manual platform" required value={manual.platform} onChange={e=>setManual({...manual,platform:e.target.value})} className="rounded-inset border border-hairline bg-panel-soft px-3 py-2 text-body"/><input aria-label="Manual URL" placeholder="URL (optional)" value={manual.url} onChange={e=>setManual({...manual,url:e.target.value})} className="rounded-inset border border-hairline bg-panel-soft px-3 py-2 text-body"/></div><textarea aria-label="Manual opportunity content" required rows={3} placeholder="Relevant post or conversation" value={manual.content} onChange={e=>setManual({...manual,content:e.target.value})} className="mt-2 w-full rounded-inset border border-hairline bg-panel-soft p-3 text-body"/><button className="mt-2 rounded-inset bg-action px-3 py-2 text-body">Add and classify</button>{manualMessage&&<p className="mt-2 text-meta text-ink-dim">{manualMessage}</p>}</form>
  <div className="mt-4 flex flex-wrap gap-2"><select aria-label="Platform" value={platform} onChange={e=>setPlatform(e.target.value)} className="rounded-inset border border-hairline bg-panel px-2 py-1 text-body"><option>ALL</option>{['reddit','twitter','hackernews'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Hypothesis" value={hypothesis} onChange={e=>setHypothesis(e.target.value)} className="rounded-inset border border-hairline bg-panel px-2 py-1 text-body"><option>ALL</option>{['H1','H2','H3','H4','H5'].map(x=><option key={x}>{x}</option>)}</select><label className="text-body text-ink-dim">Minimum <input aria-label="Minimum score" type="number" min="0" max="100" value={minimum} onChange={e=>setMinimum(Number(e.target.value))} className="ml-1 w-16 rounded-inset border border-hairline bg-panel px-2 py-1"/></label></div><div className="mt-5 space-y-3">{shown.map(x=><ReviewCard key={x.id} item={x} reload={load}/>)}</div></section>;
}

function Learnings() {
  type Row={key:string;acted:number;replies:number;replyRate:number|null;signups:number;signupRate:number|null;connectedProjects:number;connectedProjectRate:number|null;smallSample:boolean};type Data={byHypothesis:Row[];byPlatform:Row[];byAudience:Row[];byResponseMode:Row[];byDiscoverySource:Row[];summary:string};const [data,setData]=useState<Data|null>(null);useEffect(()=>{api.get<Data>('/api/ops/distribution/learnings').then(setData);},[]);if(!data)return null;const pct=(x:number|null)=>x===null?'—':`${Math.round(x*100)}%`;const table=(title:string,rows:Row[])=><section><h2 className="font-display text-xl text-ink">{title}</h2><div className="mt-2 overflow-x-auto"><table className="w-full text-left text-body"><thead className="text-ink-quiet"><tr><th>Group</th><th>Acted</th><th>Reply rate</th><th>Signup rate</th><th>Connected-project rate</th></tr></thead><tbody>{rows.map(r=><tr key={r.key} className="border-t border-hairline"><td className="py-2">{humanize(r.key)}{r.smallSample&&<span className="ml-2 text-meta text-ink-quiet">small sample</span>}</td><td>{r.acted}</td><td>{pct(r.replyRate)}</td><td>{pct(r.signupRate)}</td><td>{pct(r.connectedProjectRate)}</td></tr>)}</tbody></table></div></section>;return <div className="space-y-7"><section><p className="text-label font-semibold uppercase tracking-widest text-ink-quiet">Learnings</p><h1 className="mt-2 font-display text-3xl text-ink">Evidence before conclusions.</h1><p className="mt-3 text-body text-ink-dim">{data.summary}</p></section>{table('Machine-found vs human-found',data.byDiscoverySource)}{table('By hypothesis',data.byHypothesis)}{table('By platform',data.byPlatform)}{table('By audience',data.byAudience)}{table('By response mode',data.byResponseMode)}</div>;
}

const humanize = (value: string) => value.toLowerCase().replaceAll('_', ' ').replace(/^./, (c) => c.toUpperCase());
function ProgramView() {
  const [program, setProgram] = useState<Program | null>(null);
  const [buska, setBuska] = useState<BuskaStatus | null>(null); const [scanMessage, setScanMessage] = useState<string | null>(null);
  const loadBuska = () => api.get<BuskaStatus>('/api/ops/distribution/providers/buska').then(setBuska);
  useEffect(() => { api.get<{ program: Program }>('/api/ops/distribution/program').then((r) => setProgram(r.program)); void loadBuska(); }, []);
  if (!program) return null;
  return <div className="space-y-8">
    <section><div className="flex items-center gap-2"><p className="text-label font-semibold uppercase tracking-widest text-ink-quiet">Program</p><span className="rounded-full bg-panel-soft px-2 py-0.5 text-meta text-ink-dim">{humanize(program.status)}</span></div><h1 className="mt-2 font-display text-3xl text-ink">{program.objective}</h1><dl className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Progress" value={`${program.currentValue} / ${program.targetValue}`}/><Metric label="Time remaining" value={program.timeRemainingDays===null?'No deadline set':`${program.timeRemainingDays} days`}/><Metric label="Budget" value={program.budgetCents?`$${(program.budgetCents/100).toFixed(2)}`:'$0 manual'}/></dl><p className="mt-4 rounded-inset bg-panel-soft p-3 text-body text-ink-dim">{program.recommendation}</p></section>
    <section><h2 className="font-display text-xl text-ink">Pain hypotheses</h2><div className="mt-3 divide-y divide-hairline rounded-card border border-hairline bg-panel">{program.hypotheses.map((h) => <div key={h.id} className="grid gap-1 p-4 sm:grid-cols-[3rem_12rem_1fr]"><span className="font-mono text-meta text-action-bright">{h.code}</span><strong className="text-body text-ink">{h.name}</strong><p className="text-body text-ink-dim">{h.description}</p></div>)}</div></section>
    <section><h2 className="font-display text-xl text-ink">Autonomy</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(program.autonomySettings).map(([key, value]) => <div key={key} className="flex items-center justify-between rounded-inset border border-hairline bg-panel px-3 py-2"><span className="text-body text-ink-dim">{humanize(key)}</span><span className="font-mono text-meta text-ink">{humanize(value)}</span></div>)}</div></section>
    <section><h2 className="font-display text-xl text-ink">Operating policy</h2><dl className="mt-3 grid gap-3 sm:grid-cols-3"><Metric label="Daily cap" value={String(program.policy.daily_action_cap)}/><Metric label="Per-platform cap" value={String(program.policy.per_platform_action_cap)}/><Metric label="Exploration slots" value={String(program.policy.hypothesis_allocation.EXPLORATION??1)}/><Metric label="Minimum score" value={String(program.policy.minimum_opportunity_score)}/><Metric label="Maximum risk" value={String(program.policy.maximum_risk)}/><Metric label="Allowed channels" value={Object.entries(program.policy.allowed_channels).filter(([,on])=>on).map(([channel])=>channel).join(', ')}/></dl></section>
    <section><h2 className="font-display text-xl text-ink">Experiments</h2><div className="mt-3 space-y-2">{program.experiments.map(e=><div key={e.id} className="rounded-inset border border-hairline bg-panel p-3"><strong className="text-body text-ink">{e.name}</strong><p className="text-meta text-ink-dim">{humanize(e.status)} · Connected projects per acted opportunity</p></div>)}</div></section>
    <section><div className="flex items-center justify-between"><div><h2 className="font-display text-xl text-ink">Buska</h2><p className="mt-1 text-body text-ink-dim">Signal infrastructure only. Buska scores never become Selvedge opportunity scores.</p></div><button type="button" disabled={!buska?.configured || buska.lastScan?.status === 'RUNNING'} onClick={() => { setScanMessage('Starting scan…'); api.post('/api/ops/distribution/providers/buska/scan', {}).then(() => { setScanMessage('Scan accepted.'); window.setTimeout(() => void loadBuska(), 800); }).catch((e) => setScanMessage(e instanceof Error ? e.message : 'The scan did not start.')); }} className="rounded-inset bg-action px-3 py-2 text-body font-medium text-ink disabled:cursor-not-allowed disabled:opacity-40">Scan now</button></div>{buska && <dl className="mt-3 grid gap-2 sm:grid-cols-2"><Metric label="Configuration" value={buska.configured ? 'Configured' : 'Not configured'}/><Metric label="Signals ingested" value={String(buska.signalsIngested)}/><Metric label="Last successful scan" value={buska.lastSuccessfulScan ? new Date(buska.lastSuccessfulScan).toLocaleString() : 'Not yet'}/><Metric label="Next scheduled scan" value={new Date(buska.nextScheduledScan).toLocaleString()}/>{buska.lastError && <Metric label="Last error" value={buska.lastError}/>}</dl>}{scanMessage && <p className="mt-2 text-meta text-ink-dim">{scanMessage}</p>}</section>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-inset border border-hairline bg-panel p-3"><dt className="text-label uppercase tracking-widest text-ink-quiet">{label}</dt><dd className="mt-1 text-body font-medium text-ink">{value}</dd></div>; }

export function OpsDistribution() {
  return <AccessGate><div className="space-y-7"><header><p className="font-mono text-meta uppercase tracking-widest text-action-bright">Private operator system</p><nav aria-label="Distribution sections" className="mt-3 flex gap-1"><NavLink to="/ops/distribution/today" className={tabClass}>Today</NavLink><NavLink to="/ops/distribution/learnings" className={tabClass}>Learnings</NavLink><NavLink to="/ops/distribution/program" className={tabClass}>Program</NavLink></nav></header><Routes><Route index element={<Navigate to="/ops/distribution/today" replace/>}/><Route path="today" element={<Today/>}/><Route path="learnings" element={<Learnings/>}/><Route path="program" element={<ProgramView/>}/></Routes></div></AccessGate>;
}
