import { useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { AgentChip } from '../components/AgentChip.js';
import { SelvedgeMark } from '../components/Logo.js';

type TourView = 'migration' | 'agents' | 'health';
const views: Array<{ id: TourView; label: string; short: string }> = [
  { id: 'migration', label: 'Migration', short: 'Bring it over' },
  { id: 'agents', label: 'Agent review', short: 'Ask more than one' },
  { id: 'health', label: 'Health', short: 'Catch the problem' },
];

function MigrationView() {
  return <><section className="tour-main"><div className="tour-heading"><div><p>THREADLINE WHOLESALE / MIGRATION</p><h2>Bring Threadline over from Replit</h2></div><span className="tour-state tour-state-good">Preview ready</span></div><div className="tour-message"><span>YOU</span><p>Move Threadline into Selvedge without interrupting retailer orders.</p></div><div className="tour-migration-card"><div className="tour-card-heading"><div><span>MIGRATION AGENT</span><strong>Private copy verified</strong></div><b>6/7 complete</b></div><ol className="tour-progress"><li className="done">Inventory</li><li className="done">Repository</li><li className="done">Database</li><li className="done">Secrets</li><li className="done">Preview</li><li className="done">Verify</li><li>Approve</li></ol><div className="tour-found"><span>✓ React storefront</span><span>✓ Postgres</span><span>✓ Distributor API</span><span>✓ 4 scheduled jobs</span><span>○ Production credentials</span></div><p className="tour-note">Original Replit app is still serving orders.</p></div></section><aside className="tour-side"><div className="tour-side-tabs"><b>Preview</b><span>Context</span><span>History</span></div><div className="tour-browser"><div><i/><i/><i/><span>private-preview.selvedge.work</span></div><main><small>THREADLINE</small><h3>Wholesale ordering,<br/>without the email chains.</h3><p>Fall delivery window · 128 styles available</p><button>Start an order</button></main></div><div className="tour-verification"><span>✓ Desktop</span><span>✓ Mobile</span><span>✓ Sign in</span><span>✓ Submit order</span></div></aside></>;
}

function AgentsView() {
  return <><section className="tour-main"><div className="tour-heading"><div><p>THREADLINE WHOLESALE / CONVERSATION</p><h2>Review distributor submissions</h2></div><span className="tour-state">2 agents</span></div><div className="tour-message"><span>YOU</span><p>Retailers say some orders look submitted but never reach the distributor. <b>@claude</b> and <b>@gpt</b>, investigate independently.</p></div><div className="tour-agent-grid"><article><div><AgentChip agent="claude"/><strong>Claude</strong></div><p>The order is marked submitted before the distributor responds. A timeout leaves the retailer with a confirmation for an order the distributor never accepted.</p><small>Best fix: wait for distributor acceptance before confirming.</small></article><article><div><AgentChip agent="gpt"/><strong>GPT</strong></div><p>I agree on the failure, but waiting synchronously will make checkout fragile. Save the order as pending, retry safely, and confirm only after a distributor receipt exists.</p><small>Best fix: durable queue with idempotent retries.</small></article></div><div className="tour-decision"><span>SELVEDGE</span><p><strong>Shared conclusion:</strong> confirmation happens too early. Queue the submission, require a distributor receipt, and alert on orders pending longer than 15 minutes.</p></div></section><aside className="tour-side tour-context"><div className="tour-side-tabs"><b>Context</b><span>Preview</span><span>History</span></div><p className="tour-kicker">WHAT GOVERNS THIS WORK</p><h3>Threadline Wholesale</h3><div className="tour-context-block"><small>CURRENT BUILDER</small><p><AgentChip agent="codex"/> Codex</p><a>Change builder — context stays here</a></div><p className="tour-kicker">EVIDENCE USED BY BOTH AGENTS</p><ul><li>Order submission service</li><li>Distributor API contract</li><li>18 delayed order records</li><li>Production request logs</li></ul><button className="tour-action">Send plan to Codex →</button></aside></>;
}

function HealthView() {
  return <><section className="tour-main"><div className="tour-heading"><div><p>HEALTH CENTER / THREADLINE WHOLESALE</p><h2>Distributor orders are delayed</h2></div><span className="tour-state tour-state-bad">Action needed</span></div><div className="tour-incident"><div><span className="tour-incident-dot"/><div><small>INCIDENT OPENED 1H 47M AGO</small><h3>Order submissions are not reaching two distributors</h3></div></div><p>Retailers receive an order number, but distributor receipts are missing. New submissions have been paused to prevent more false confirmations.</p><dl><div><dt>18</dt><dd>orders delayed</dd></div><div><dt>7</dt><dd>retailers affected</dd></div><div><dt>2</dt><dd>distributors affected</dd></div></dl></div><div className="tour-timeline"><div><time>09:14</time><p><strong>First missing receipt</strong><span>Northline Distribution did not acknowledge order TW-1842.</span></p></div><div><time>10:01</time><p><strong>Failure confirmed</strong><span>Three consecutive submission checks failed.</span></p></div><div><time>10:04</time><p><strong>Selvedge paused confirmations</strong><span>Retailers now see “Pending distributor” instead of a false success.</span></p></div><div><time>10:18</time><p><strong>Fix ready to review</strong><span>Codex added durable retries and receipt-based confirmation.</span></p></div></div></section><aside className="tour-side tour-health-side"><div className="tour-side-tabs"><b>Incident</b><span>Checks</span><span>History</span></div><p className="tour-kicker">CUSTOMER IMPACT</p><h3>Orders are delayed.<br/>None were lost.</h3><div className="tour-health-callout"><small>PROTECTIVE ACTION</small><strong>False confirmations stopped</strong><p>New orders remain pending until the distributor accepts them.</p></div><div className="tour-health-checks"><p><span>●</span> Storefront available</p><p><span>●</span> Database healthy</p><p className="bad"><span>●</span> Distributor receipts failing</p><p><span>●</span> Retailer notifications available</p></div><button className="tour-action">Review the fix →</button></aside></>;
}

export function ProductTour({ embedded = false }: { embedded?: boolean }) {
  const [params, setParams] = useSearchParams();
  const initial = params.get('view');
  const [view, setView] = useState<TourView>(initial === 'agents' || initial === 'health' ? initial : 'migration');
  const content = useMemo(() => view === 'migration' ? <MigrationView/> : view === 'agents' ? <AgentsView/> : <HealthView/>, [view]);
  function choose(next: TourView) { setView(next); if (!embedded) setParams({ view: next }, { replace: true }); }
  return <div className={`product-tour ${embedded ? 'product-tour-embedded' : 'product-tour-page'}`}>{!embedded&&<header className="tour-public-nav"><Link to="/"><SelvedgeMark className="h-7 w-7"/></Link><span>Live product tour</span><Link to="/request-invite">Request an invite</Link></header>}<div className="tour-shell"><header className="tour-topbar"><div><SelvedgeMark className="h-6 w-6"/><strong>Selvedge</strong><span>Threadline Wholesale</span></div>{embedded?<Link to={`/product-tour?view=${view}`} target="_blank">Open full screen ↗</Link>:<span>Read-only seeded project</span>}</header><nav className="tour-view-tabs" aria-label="Product tour">{views.map(item=><button key={item.id} type="button" className={view===item.id?'active':''} onClick={()=>choose(item.id)}><span>{item.label}</span><small>{item.short}</small></button>)}</nav><div className="tour-workspace" key={view}>{content}</div></div></div>;
}
