import {and,eq,gte} from 'drizzle-orm';import type {Db} from '../db/client.js';import {distributionActions,distributionHypotheses,distributionOpportunities,distributionOutcomes,distributionPrograms,distributionSignals} from '../db/schema/index.js';import {DISTRIBUTION_SCOPE} from './domain.js';import {SELVEDGE_PROGRAM_ID} from './store.js';
export type DistributionPolicy={daily_action_cap:number;per_platform_action_cap:number;minimum_opportunity_score:number;maximum_risk:number;allowed_channels:Record<string,boolean>;hypothesis_allocation:Record<string,number>};
const fallback:DistributionPolicy={daily_action_cap:10,per_platform_action_cap:5,minimum_opportunity_score:75,maximum_risk:40,allowed_channels:{reddit:true,twitter:true,hackernews:true},hypothesis_allocation:{H1:2,H2:2,H3:2,H4:2,H5:1,EXPLORATION:1}};
/** A simple evidence-weighted allocation, not reinforcement learning. The +1/+4 smoothing prevents one early conversion from dominating. Least-tested cells get exploration slots first. Actions already taken today consume the global and platform caps. */
export async function planDistributionDay(db:Db){
 const [program]=await db.select().from(distributionPrograms).where(eq(distributionPrograms.id,SELVEDGE_PROGRAM_ID));const policy={...fallback,...(program?.policy as Partial<DistributionPolicy>??{})};
 const rows=await db.select({o:distributionOpportunities,s:distributionSignals,h:distributionHypotheses}).from(distributionOpportunities).leftJoin(distributionSignals,eq(distributionOpportunities.signalId,distributionSignals.id)).leftJoin(distributionHypotheses,eq(distributionOpportunities.hypothesisId,distributionHypotheses.id)).where(eq(distributionOpportunities.orgId,DISTRIBUTION_SCOPE));const outcomes=await db.select().from(distributionOutcomes).where(eq(distributionOutcomes.orgId,DISTRIBUTION_SCOPE));
 const start=new Date();start.setHours(0,0,0,0);const today=await db.select({a:distributionActions,s:distributionSignals}).from(distributionActions).innerJoin(distributionOpportunities,eq(distributionActions.opportunityId,distributionOpportunities.id)).leftJoin(distributionSignals,eq(distributionOpportunities.signalId,distributionSignals.id)).where(and(eq(distributionActions.orgId,DISTRIBUTION_SCOPE),gte(distributionActions.actedAt,start)));const platformCount=new Map<string,number>();for(const r of today){const p=r.s?.platform??'UNKNOWN';platformCount.set(p,(platformCount.get(p)??0)+1);}
 const evidence=new Map<string,{acted:number;projects:number}>();for(const r of rows){const key=`${r.h?.code??'OTHER'}:${r.s?.platform??'UNKNOWN'}`;const e=evidence.get(key)??{acted:0,projects:0};if(r.o.state==='ACTED')e.acted++;e.projects+=outcomes.filter(x=>x.opportunityId===r.o.id&&x.outcomeType==='PROJECT_CONNECTED').length;evidence.set(key,e);}
 const candidates=rows.filter(r=>r.o.state==='READY'&&r.o.overallScore>=policy.minimum_opportunity_score&&r.o.riskScore<=policy.maximum_risk&&Boolean(policy.allowed_channels[r.s?.platform??'']));const scored=candidates.map(r=>{const hypothesis=r.h?.code??'OTHER',platform=r.s?.platform??'UNKNOWN',e=evidence.get(`${hypothesis}:${platform}`)??{acted:0,projects:0};return{...r,hypothesis,platform,evidence:e,evidenceScore:(e.projects+1)/(e.acted+4)};}).sort((a,b)=>b.evidenceScore-a.evidenceScore||b.o.overallScore-a.o.overallScore);
 const recommendations:Array<{opportunityId:string;hypothesis:string;platform:string;allocationType:'EXPLORATION'|'EXPLOITATION';whyOpportunity:string;whyHypothesis:string;whyChannel:string;evidence:string}>=[];const hypCount=new Map<string,number>(),remaining=Math.max(0,policy.daily_action_cap-today.length);const add=(r:typeof scored[number],kind:'EXPLORATION'|'EXPLOITATION')=>{if(recommendations.some(x=>x.opportunityId===r.o.id)||recommendations.length>=remaining)return;if((platformCount.get(r.platform)??0)>=policy.per_platform_action_cap)return;if(kind==='EXPLOITATION'&&(hypCount.get(r.hypothesis)??0)>=(policy.hypothesis_allocation[r.hypothesis]??policy.daily_action_cap))return;platformCount.set(r.platform,(platformCount.get(r.platform)??0)+1);hypCount.set(r.hypothesis,(hypCount.get(r.hypothesis)??0)+1);recommendations.push({opportunityId:r.o.id,hypothesis:r.hypothesis,platform:r.platform,allocationType:kind,whyOpportunity:`Score ${r.o.overallScore}, risk ${r.o.riskScore}; ${r.o.reasoning}`,whyHypothesis:kind==='EXPLORATION'?`${r.hypothesis} has only ${r.evidence.acted} acted examples, so it preserves learning.`:`${r.hypothesis} has ${r.evidence.projects} connected projects from ${r.evidence.acted} acted opportunities.`,whyChannel:`${r.platform} is allowed and remains below its daily cap.`,evidence:`Smoothed project rate ${r.evidenceScore.toFixed(2)} from ${r.evidence.acted} acted opportunities.`});};
 const explorationSlots=Math.min(remaining,Math.max(1,policy.hypothesis_allocation.EXPLORATION??1));const explore=[...scored].sort((a,b)=>a.evidence.acted-b.evidence.acted||b.o.overallScore-a.o.overallScore).slice(0,explorationSlots);for(const r of explore)add(r,'EXPLORATION');for(const r of scored)add(r,'EXPLOITATION');return{policy,recommendations,reviewedSignals:await db.select().from(distributionSignals).where(eq(distributionSignals.orgId,DISTRIBUTION_SCOPE)).then(x=>x.length),attentionCount:recommendations.length};
}
