import { Router } from 'express';
import type { Db } from '../../db/client.js';
import { distributionActions, distributionDrafts, distributionHypotheses, distributionOpportunities, distributionPrograms, distributionReferralSources, distributionSignals } from '../../db/schema/index.js';
import { DISTRIBUTION_SCOPE } from '../../distribution/domain.js';
import { ensureSelvedgeDistributionProgram } from '../../distribution/store.js';
import { and, desc, eq, inArray } from 'drizzle-orm';
import { ulid } from 'ulid';
import { batchEligible, draftOpportunity } from '../../distribution/drafting.js';
import { buildDistributionDraftClient } from '../../llm/factory.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { operatorOnly } from '../middleware/operatorOnly.js';
import { buskaStatus, configuredBuskaClient, runBuskaPipeline, type BuskaScanClient } from '../../distribution/ingestBuska.js';
import { aiLearningSummary, attributeOutcome, distributionLearnings, ensureDistributionExperiments, OUTCOME_TYPES } from '../../distribution/learnings.js';
import { planDistributionDay } from '../../distribution/planner.js';
import { ingestSignal } from '../../distribution/store.js';
import { processDistributionSignals } from '../../distribution/processSignals.js';

export function createDistributionOpsRouter(db: Db, allowed?: ReadonlySet<string>, buskaClient: () => BuskaScanClient | null = configuredBuskaClient) {
  const router = Router();
  router.post('/api/referral-source',asyncHandler(async(req,res)=>{const raw=typeof req.body?.answer==='string'?req.body.answer.trim():'';if(!raw){res.status(400).json({error:'A source answer cannot be empty.'});return;}const orgId=(req as typeof req&{orgId:string}).orgId,userId=(req as typeof req&{userId?:string|null}).userId??null;await db.insert(distributionReferralSources).values({id:ulid(),orgId,userId,rawAnswer:raw});res.status(201).json({saved:true});}));
  router.use('/api/ops/distribution', operatorOnly(allowed));
  router.get('/api/ops/distribution/access', (_req, res) => res.json({ allowed: true }));
  router.get('/api/ops/distribution/program', asyncHandler(async (_req, res) => {
    const program=await ensureSelvedgeDistributionProgram(db);const experiments=await ensureDistributionExperiments(db);const learning=await distributionLearnings(db);const planner=await planDistributionDay(db);res.json({ program:{...program,currentValue:learning.current,timeRemainingDays:program?.targetDate?Math.max(0,Math.ceil((program.targetDate.getTime()-Date.now())/86400000)):null,experiments,recommendation:learning.recommendation,planner} });
  }));
  router.get('/api/ops/distribution/today', asyncHandler(async (_req, res) => {
    await ensureSelvedgeDistributionProgram(db);
    const rows = await db.select({ opportunity: distributionOpportunities, signal: distributionSignals, hypothesis: distributionHypotheses, draft:distributionDrafts }).from(distributionOpportunities).leftJoin(distributionSignals, eq(distributionOpportunities.signalId,distributionSignals.id)).leftJoin(distributionHypotheses,eq(distributionOpportunities.hypothesisId,distributionHypotheses.id)).leftJoin(distributionDrafts,eq(distributionDrafts.opportunityId,distributionOpportunities.id)).where(and(eq(distributionOpportunities.orgId,DISTRIBUTION_SCOPE),inArray(distributionOpportunities.state,['READY','DRAFTED','APPROVED','ACTED']))).orderBy(desc(distributionOpportunities.overallScore));
    const [planner, learning] = await Promise.all([planDistributionDay(db), distributionLearnings(db)]);
    res.json({ opportunities: rows.map(({opportunity,signal,hypothesis,draft})=>({...opportunity,draft,platform:signal?.platform??null,author:signal?.authorName??signal?.authorHandle??null,content:signal?.content??null,url:signal?.url??null,publishedAt:signal?.publishedAt??null,hypothesis:hypothesis?.code??'OTHER'})), total: rows.length, currentValue: learning.current, targetValue: 50, reviewedSignals: planner.reviewedSignals, attentionCount: planner.attentionCount, planner });
  }));
  router.post('/api/ops/distribution/opportunities/:id/skip', asyncHandler(async (req,res)=>{ const [row]=await db.update(distributionOpportunities).set({state:'SKIPPED',updatedAt:new Date()}).where(and(eq(distributionOpportunities.orgId,DISTRIBUTION_SCOPE),eq(distributionOpportunities.id,req.params.id??''),inArray(distributionOpportunities.state,['READY','DRAFTED','APPROVED']))).returning(); if(!row){res.status(404).json({error:'That opportunity cannot be skipped.'});return;} await db.update(distributionDrafts).set({status:'SKIPPED',updatedAt:new Date()}).where(and(eq(distributionDrafts.orgId,DISTRIBUTION_SCOPE),eq(distributionDrafts.opportunityId,row.id))); res.json({opportunity:row}); }));
  router.get('/api/ops/distribution/drafts/metrics',asyncHandler(async(_req,res)=>{const rows=await db.select().from(distributionDrafts).where(eq(distributionDrafts.orgId,DISTRIBUTION_SCOPE));const decided=rows.filter(x=>x.status==='APPROVED'||x.status==='SKIPPED');const approved=decided.filter(x=>x.status==='APPROVED');const edited=approved.filter(x=>x.editedByHuman);res.json({total:decided.length,approvedUnchanged:approved.length-edited.length,edited:edited.length,skipped:decided.filter(x=>x.status==='SKIPPED').length});}));
  router.post('/api/ops/distribution/opportunities/:id/draft',asyncHandler(async(req,res)=>{const llm=buildDistributionDraftClient();if(!llm){res.status(503).json({error:'Response drafting is not configured.'});return;}res.json({draft:await draftOpportunity(db,llm,req.params.id??'')});}));
  router.patch('/api/ops/distribution/drafts/:id',asyncHandler(async(req,res)=>{const body=typeof req.body?.body==='string'?req.body.body.trim():'';if(!body){res.status(400).json({error:'A response cannot be empty.'});return;}const [draft]=await db.update(distributionDrafts).set({body,finalBody:body,editedByHuman:true,updatedAt:new Date()}).where(and(eq(distributionDrafts.orgId,DISTRIBUTION_SCOPE),eq(distributionDrafts.id,req.params.id??''))).returning();if(!draft){res.status(404).json({error:'Draft not found.'});return;}res.json({draft});}));
  router.post('/api/ops/distribution/drafts/:id/approve',asyncHandler(async(req,res)=>{const [draft]=await db.update(distributionDrafts).set({status:'APPROVED',finalBody:distributionDrafts.body,updatedAt:new Date()}).where(and(eq(distributionDrafts.orgId,DISTRIBUTION_SCOPE),eq(distributionDrafts.id,req.params.id??''))).returning();if(!draft){res.status(404).json({error:'Draft not found.'});return;}await db.update(distributionOpportunities).set({state:'APPROVED',updatedAt:new Date()}).where(eq(distributionOpportunities.id,draft.opportunityId));res.json({draft});}));
  router.post('/api/ops/distribution/opportunities/:id/posted',asyncHandler(async(req,res)=>{const [o]=await db.update(distributionOpportunities).set({state:'ACTED',updatedAt:new Date()}).where(and(eq(distributionOpportunities.orgId,DISTRIBUTION_SCOPE),eq(distributionOpportunities.id,req.params.id??''),eq(distributionOpportunities.state,'APPROVED'))).returning();if(!o){res.status(404).json({error:'That response is not approved.'});return;}const [d]=await db.select().from(distributionDrafts).where(eq(distributionDrafts.opportunityId,o.id)).orderBy(desc(distributionDrafts.version)).limit(1);await db.insert(distributionActions).values({id:ulid(),orgId:DISTRIBUTION_SCOPE,opportunityId:o.id,actionType:'REPLY',finalContent:d?.finalBody??d?.body??null,externalUrl:typeof req.body?.url==='string'?req.body.url:null,actedAt:new Date(),actor:'operator',status:'POSTED'});res.json({opportunity:o});}));
  router.post('/api/ops/distribution/drafts/approve-high-confidence',asyncHandler(async(_req,res)=>{const rows=await db.select({o:distributionOpportunities,d:distributionDrafts}).from(distributionDrafts).innerJoin(distributionOpportunities,eq(distributionDrafts.opportunityId,distributionOpportunities.id)).where(and(eq(distributionDrafts.orgId,DISTRIBUTION_SCOPE),eq(distributionDrafts.status,'DRAFTED')));const eligible=rows.filter(x=>batchEligible(x.o,x.d));for(const {o,d} of eligible){await db.update(distributionDrafts).set({status:'APPROVED',finalBody:d.body,updatedAt:new Date()}).where(eq(distributionDrafts.id,d.id));await db.update(distributionOpportunities).set({state:'APPROVED',updatedAt:new Date()}).where(eq(distributionOpportunities.id,o.id));}res.json({approved:eligible.length});}));
  router.get('/api/ops/distribution/learnings', asyncHandler(async(_req,res)=>{const learning=await distributionLearnings(db);const llm=buildDistributionDraftClient();const summary=llm?await aiLearningSummary(llm,{byHypothesis:learning.byHypothesis,byPlatform:learning.byPlatform},learning.summary):learning.summary;res.json({...learning,summary});}));
  router.post('/api/ops/distribution/opportunities/:id/outcomes',asyncHandler(async(req,res)=>{const type=req.body?.type;if(!OUTCOME_TYPES.includes(type)){res.status(400).json({error:'Unknown outcome type.'});return;}const confidence=req.body?.confidence;if(!['confirmed','likely','possible'].includes(confidence)){res.status(400).json({error:'Choose confirmed, likely, or possible confidence.'});return;}res.status(201).json({outcome:await attributeOutcome(db,{opportunityId:req.params.id??'',type,confidence,reason:typeof req.body?.reason==='string'?req.body.reason:undefined,targetId:typeof req.body?.targetId==='string'?req.body.targetId:undefined})});}));
  router.post('/api/ops/distribution/opportunities/manual',asyncHandler(async(req,res)=>{const platform=typeof req.body?.platform==='string'?req.body.platform.trim().toLowerCase():'';const content=typeof req.body?.content==='string'?req.body.content.trim():'';const url=typeof req.body?.url==='string'?req.body.url.trim():null;if(!platform||!content){res.status(400).json({error:'Platform and content are required.'});return;}const signal=(await ingestSignal(db,{provider:'manual',platform,url,content,rawPayload:{manual:true},dedupeKey:`manual:${url||ulid()}`})).signal;const llm=buildDistributionDraftClient();if(!llm){res.status(503).json({error:'Opportunity classification is not configured.'});return;}await processDistributionSignals(db,llm);await db.update(distributionOpportunities).set({discoverySource:'HUMAN_FOUND'}).where(eq(distributionOpportunities.signalId,signal.id));res.status(201).json({signalId:signal.id});}));
  router.patch('/api/ops/distribution/program/policy',asyncHandler(async(req,res)=>{const [program]=await db.update(distributionPrograms).set({policy:req.body,updatedAt:new Date()}).where(and(eq(distributionPrograms.orgId,DISTRIBUTION_SCOPE),eq(distributionPrograms.id,'distribution_program_selvedge'))).returning();res.json({policy:program?.policy});}));
  router.get('/api/ops/distribution/providers/buska', asyncHandler(async (_req, res) => { res.json(await buskaStatus(db)); }));
  router.post('/api/ops/distribution/providers/buska/scan', asyncHandler(async (_req, res) => {
    const client = buskaClient(); if (!client) { res.status(503).json({ error: 'Buska is not configured.' }); return; }
    const status = await buskaStatus(db); if (status.lastScan?.status === 'RUNNING') { res.status(409).json({ error: 'A Buska scan is already running.' }); return; }
    void runBuskaPipeline(db, client).catch((error) => console.error('manual Buska scan failed:', error));
    res.status(202).json({ accepted: true });
  }));
  return router;
}
